apiVersion: v1
kind: Service
metadata:
  name: {{ include "playground.fullname" . }}
  labels:
    {{- include "playground.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports -}}
    - port: {{ .number }}
      protocol: TCP
      targetPort: {{ .targetPort }}
      name: {{ .name }}
  {{- end }}
  selector:
    {{- include "playground.selectorLabels" . | nindent 4 }}
